llm:
  default: "openai"
  options:
    - openai
    - gemini

openai:
  api_key_env: "OPENAI_API_KEY"
  model: "gpt-3.5-turbo"  # or whatever model you're using

gemini:
  api_key_env: "GOOGLE_API_KEY"
  model: "gemini-pro-vision"  # or whatever the correct model name is